import scipy.io
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.model_selection import train_test_split
from sklearn.decomposition import TruncatedSVD
import matplotlib.pyplot as plt
from tqdm import tqdm
import os
import pandas as pd
from PIL import Image


# this is a series of data generated by reaction-diffusion equation, we want to use the uv map of `t` to predict the uv map of `t+1`
# 512x512 is the spatial dim, 201 is the time dim

# Apply SVD for dimensionality reduction
def apply_svd(data, n_components=100):
    """
    Apply SVD to reduce dimensionality of spatial data

    Args:
        data: Input data of shape (height, width, time)
        n_components: Number of SVD components to keep

    Returns:
        reduced_data: Data with reduced spatial dimensions
        svd_model: Fitted SVD model for later reconstruction
    """
    # Reshape to (time, height*width)
    height, width, time = data.shape
    data_reshaped = np.zeros((time, height * width))

    # Manual reshaping to avoid memory issues
    for t in range(time):
        data_reshaped[t] = data[:, :, t].flatten()

    # Apply SVD
    svd = TruncatedSVD(n_components=n_components)
    reduced_data = svd.fit_transform(data_reshaped)

    print(f"Explained variance ratio: {svd.explained_variance_ratio_.sum():.4f}")

    return reduced_data, svd

# Function to prepare data for time series prediction
def load_rd_data_svd(u_reduced, v_reduced):
    """
    Create input-output pairs for time series prediction using SVD-reduced data

    Args:
        u_reduced: SVD-reduced u component data
        v_reduced: SVD-reduced v component data

    Returns:
        X: Input features (u_t, v_t)
        Y: Target outputs (u_t+1, v_t+1)
    """
    X, Y = [], []
    for i in range(u_reduced.shape[0] - 1):
        # Stack u and v as features
        x_combined = np.concatenate([u_reduced[i], v_reduced[i]])  # Shape: (2*n_components)
        y_combined = np.concatenate([u_reduced[i+1], v_reduced[i+1]])  # Shape: (2*n_components)

        X.append(x_combined)
        Y.append(y_combined)

    return np.array(X), np.array(Y)

# UNet-inspired architecture for SVD-reduced data
class UNetSVDBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(UNetSVDBlock, self).__init__()
        self.block = nn.Sequential(
            nn.Linear(in_channels, out_channels),
            nn.ReLU(),
            nn.BatchNorm1d(out_channels),
            nn.Linear(out_channels, out_channels),
            nn.ReLU(),
            nn.BatchNorm1d(out_channels)
        )

    def forward(self, x):
        return self.block(x)

class UNetSVD(nn.Module):
    def __init__(self, input_size, output_size=None):
        super(UNetSVD, self).__init__()
        if output_size is None:
            output_size = input_size

        # Encoder path
        self.enc1 = UNetSVDBlock(input_size, 256)
        self.enc2 = UNetSVDBlock(256, 512)
        self.enc3 = UNetSVDBlock(512, 1024)

        # Bottleneck
        self.bottleneck = UNetSVDBlock(1024, 2048)

        # Decoder path with skip connections
        self.dec3 = UNetSVDBlock(2048 + 1024, 1024)  # +1024 for skip connection
        self.dec2 = UNetSVDBlock(1024 + 512, 512)    # +512 for skip connection
        self.dec1 = UNetSVDBlock(512 + 256, 256)     # +256 for skip connection

        # Final output layer
        self.final = nn.Linear(256, output_size)

    def forward(self, x):
        # Encoder
        enc1 = self.enc1(x)
        enc2 = self.enc2(enc1)
        enc3 = self.enc3(enc2)

        # Bottleneck
        bottleneck = self.bottleneck(enc3)

        # Decoder with skip connections
        dec3 = self.dec3(torch.cat([bottleneck, enc3], dim=1))
        dec2 = self.dec2(torch.cat([dec3, enc2], dim=1))
        dec1 = self.dec1(torch.cat([dec2, enc1], dim=1))

        # Final output
        output = self.final(dec1)

        return output

# Training function
def train_model(model, train_loader, test_loader, criterion, optimizer, num_epochs=30):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    model = model.to(device)
    train_losses = []
    test_losses = []

    for epoch in range(num_epochs):
        # Training
        model.train()
        train_running_loss = 0.0
        progress_bar = tqdm(train_loader, desc=f"Epoch {epoch+1}/{num_epochs}")

        for inputs, targets in progress_bar:
            inputs, targets = inputs.to(device), targets.to(device)

            optimizer.zero_grad()
            outputs = model(inputs)
            loss = criterion(outputs, targets)
            loss.backward()
            optimizer.step()

            train_running_loss += loss.item()
            progress_bar.set_postfix({"loss": loss.item()})

        epoch_train_loss = train_running_loss / len(train_loader.dataset)
        train_losses.append(epoch_train_loss)

        # Testing
        model.eval()
        test_running_loss = 0.0

        with torch.no_grad():
            for inputs, targets in test_loader:
                inputs, targets = inputs.to(device), targets.to(device)
                outputs = model(inputs)
                loss = criterion(outputs, targets)
                test_running_loss += loss.item()

        epoch_test_loss = test_running_loss / len(test_loader.dataset)
        test_losses.append(epoch_test_loss)

        print(f"Epoch {epoch+1}/{num_epochs} - Train Loss: {epoch_train_loss:.6f}, Test Loss: {epoch_test_loss:.6f}")

    return model, train_losses, test_losses

# Visualization function for SVD-based model
def visualize_svd_prediction(model, X_test_tensor, Y_test_tensor, u_svd, v_svd, idx=0, save_dir='p2', dataset_name='combined'):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.eval()

    with torch.no_grad():
        input_sample = X_test_tensor[idx:idx+1].to(device)
        true_output = Y_test_tensor[idx].cpu().numpy()
        predicted_output = model(input_sample).cpu().numpy()[0]

    # Split the output into u and v components
    n_components = true_output.shape[0] // 2
    true_u_reduced = true_output[:n_components]
    true_v_reduced = true_output[n_components:]
    pred_u_reduced = predicted_output[:n_components]
    pred_v_reduced = predicted_output[n_components:]

    # Reconstruct the original spatial dimensions
    true_u_flat = u_svd.inverse_transform(true_u_reduced.reshape(1, -1))
    true_v_flat = v_svd.inverse_transform(true_v_reduced.reshape(1, -1))
    pred_u_flat = u_svd.inverse_transform(pred_u_reduced.reshape(1, -1))
    pred_v_flat = v_svd.inverse_transform(pred_v_reduced.reshape(1, -1))

    # Reshape to original dimensions
    true_u_reconstructed = true_u_flat.reshape(512, 512)
    true_v_reconstructed = true_v_flat.reshape(512, 512)
    pred_u_reconstructed = pred_u_flat.reshape(512, 512)
    pred_v_reconstructed = pred_v_flat.reshape(512, 512)

    # Calculate errors
    u_error = np.abs(true_u_reconstructed - pred_u_reconstructed)
    v_error = np.abs(true_v_reconstructed - pred_v_reconstructed)

    # Create a figure with subplots for u and v components
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))

    # Plot u component
    im0 = axes[0, 0].imshow(true_u_reconstructed, cmap='viridis')
    axes[0, 0].set_title('True u')
    plt.colorbar(im0, ax=axes[0, 0])

    im1 = axes[0, 1].imshow(pred_u_reconstructed, cmap='viridis')
    axes[0, 1].set_title('Predicted u')
    plt.colorbar(im1, ax=axes[0, 1])

    im2 = axes[0, 2].imshow(u_error, cmap='hot')
    axes[0, 2].set_title('Absolute Error u')
    plt.colorbar(im2, ax=axes[0, 2])

    # Plot v component
    im3 = axes[1, 0].imshow(true_v_reconstructed, cmap='viridis')
    axes[1, 0].set_title('True v')
    plt.colorbar(im3, ax=axes[1, 0])

    im4 = axes[1, 1].imshow(pred_v_reconstructed, cmap='viridis')
    axes[1, 1].set_title('Predicted v')
    plt.colorbar(im4, ax=axes[1, 1])

    im5 = axes[1, 2].imshow(v_error, cmap='hot')
    axes[1, 2].set_title('Absolute Error v')
    plt.colorbar(im5, ax=axes[1, 2])

    plt.tight_layout()
    save_path = os.path.join(save_dir, f'prediction_visualization_{dataset_name}.png')
    plt.savefig(save_path, dpi=300)
    plt.show()

    # Save the prediction data
    # Sample a subset of points to reduce file size
    indices = np.random.choice(512*512, size=10000, replace=False)
    u_prediction_data = {
        'True_u': true_u_reconstructed.flat[indices],
        'Predicted_u': pred_u_reconstructed.flat[indices],
        'Absolute_Error_u': u_error.flat[indices]
    }
    v_prediction_data = {
        'True_v': true_v_reconstructed.flat[indices],
        'Predicted_v': pred_v_reconstructed.flat[indices],
        'Absolute_Error_v': v_error.flat[indices]
    }

    # Save to CSV
    pd.DataFrame(u_prediction_data).to_csv(os.path.join(save_dir, f'u_prediction_data_{dataset_name}.csv'), index=False)
    pd.DataFrame(v_prediction_data).to_csv(os.path.join(save_dir, f'v_prediction_data_{dataset_name}.csv'), index=False)

    # Calculate and save error metrics
    error_metrics = {
        'u_mae': np.mean(u_error),
        'v_mae': np.mean(v_error),
        'u_mse': np.mean(u_error**2),
        'v_mse': np.mean(v_error**2)
    }

    with open(os.path.join(save_dir, f'error_metrics_{dataset_name}.txt'), 'w') as f:
        for metric, value in error_metrics.items():
            f.write(f"{metric}: {value:.6f}\n")

    return error_metrics

# Main function
def main():
# Load and prepare data
    mat0 = scipy.io.loadmat('/home/cyl/Datasets/DataMiningCourse/RD/reaction_diffusion_big_0.mat')
    mat1 = scipy.io.loadmat('/home/cyl/Datasets/DataMiningCourse/RD/reaction_diffusion_big_1.mat')

    # Extract u and v components from both datasets
    u0, v0 = mat0['u'], mat0['v']
    u1, v1 = mat1['u'], mat1['v']

    # Verify shapes
    assert u0.shape == v0.shape, "Shape mismatch in dataset 0"
    assert u1.shape == v1.shape, "Shape mismatch in dataset 1"
    assert u0.shape == u1.shape, "Shape mismatch between datasets"
    print("Dataset 0 shape:", u0.shape)
    print("Dataset 1 shape:", u1.shape)

    # Combine datasets for SVD
    # We'll concatenate along the time dimension (axis 2)
    u_combined = np.concatenate([u0, u1], axis=2)
    v_combined = np.concatenate([v0, v1], axis=2)
    print("Combined dataset shape:", u_combined.shape)
    # Create output directory
    save_dir = 'p2'
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)
        print(f"Created directory: {save_dir}")

    # Set SVD components
    n_svd_components = 200
    print(f"Applying SVD with {n_svd_components} components...")

    # Reshape data for SVD processing
    # Original data shape is (512, 512, 201) - height, width, time
    print("Preparing data for SVD...")

    # Apply SVD to combined u and v components
    print("Applying SVD to combined u component...")
    u_reduced, u_svd = apply_svd(u_combined, n_components=n_svd_components)
    print("Applying SVD to combined v component...")
    v_reduced, v_svd = apply_svd(v_combined, n_components=n_svd_components)

    print(f"Reduced data shapes: u = {u_reduced.shape}, v = {v_reduced.shape}")

    # Split the reduced data back into the two datasets
    time_split = u0.shape[2]
    u0_reduced = u_reduced[:time_split]
    u1_reduced = u_reduced[time_split:]
    v0_reduced = v_reduced[:time_split]
    v1_reduced = v_reduced[time_split:]

    print(f"Split reduced data shapes: dataset 0 u = {u0_reduced.shape}, v = {v0_reduced.shape}")
    print(f"Split reduced data shapes: dataset 1 u = {u1_reduced.shape}, v = {v1_reduced.shape}")

    # Create input-output pairs for both datasets
    X0, Y0 = load_rd_data_svd(u0_reduced, v0_reduced)
    X1, Y1 = load_rd_data_svd(u1_reduced, v1_reduced)

    # Combine datasets
    X = np.vstack([X0, X1])
    Y = np.vstack([Y0, Y1])

    print(f"Dataset 0: X shape = {X0.shape}, Y shape = {Y0.shape}")
    print(f"Dataset 1: X shape = {X1.shape}, Y shape = {Y1.shape}")
    print(f"Combined: X shape = {X.shape}, Y shape = {Y.shape}")

    # Split data into training and testing sets
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)
    print(f"Training set: X shape = {X_train.shape}, Y shape = {Y_train.shape}")
    print(f"Testing set: X shape = {X_test.shape}, Y shape = {Y_test.shape}")

    # Convert to PyTorch tensors
    X_train_tensor = torch.FloatTensor(X_train)
    Y_train_tensor = torch.FloatTensor(Y_train)
    X_test_tensor = torch.FloatTensor(X_test)
    Y_test_tensor = torch.FloatTensor(Y_test)

    # Create DataLoader
    train_dataset = TensorDataset(X_train_tensor, Y_train_tensor)
    test_dataset = TensorDataset(X_test_tensor, Y_test_tensor)
    train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=64, shuffle=True)

    # Initialize model
    input_size = X_train_tensor.shape[1]  # 2 * n_svd_components
    model = UNetSVD(input_size=input_size)
    model_name = model.__class__.__name__

    # Define loss function and optimizer
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    # Train model
    print(f"Training {model_name} model...")
    trained_model, train_losses, test_losses = train_model(
        model, train_loader, test_loader, criterion, optimizer, num_epochs=1000
    )

    # Save loss values to CSV
    loss_df = pd.DataFrame({
        'Epoch': list(range(1, len(train_losses) + 1)),
        'Training_Loss': train_losses,
        'Testing_Loss': test_losses
    })
    loss_df.to_csv(os.path.join(save_dir, 'loss_data.csv'), index=False)

    # Plot training and testing loss
    plt.figure(figsize=(10, 5))
    plt.plot(train_losses, label='Training Loss')
    plt.plot(test_losses, label='Testing Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.title(f'Training and Testing Loss - {model_name}')
    plt.savefig(os.path.join(save_dir, 'loss_curves.png'))
    plt.show()

    # Visualize predictions for both datasets
    print("Visualizing predictions...")

    # Find indices in the test set that correspond to each dataset
    # We'll use the first test sample from each dataset for visualization
    dataset0_idx = 0  # Just use the first test sample for dataset 0
    dataset1_idx = len(X_test) // 2  # Use a sample from the middle for dataset 1

    # Visualize predictions for dataset 0
    error_metrics0 = visualize_svd_prediction(
        trained_model, X_test_tensor, Y_test_tensor, u_svd, v_svd,
        idx=dataset0_idx, save_dir=save_dir, dataset_name='dataset0'
    )

    # Visualize predictions for dataset 1
    error_metrics1 = visualize_svd_prediction(
        trained_model, X_test_tensor, Y_test_tensor, u_svd, v_svd,
        idx=dataset1_idx, save_dir=save_dir, dataset_name='dataset1'
    )

    # Save the model
    model_path = os.path.join(save_dir, f'{model_name}_prediction_model.pth')
    torch.save(trained_model.state_dict(), model_path)

    # Save model architecture information
    with open(os.path.join(save_dir, 'model_info.txt'), 'w') as f:
        f.write(f"Model Architecture: {model_name}\n")
        f.write(f"SVD Components: {n_svd_components}\n")
        f.write(f"Input Size: {input_size} (2 * {n_svd_components})\n")
        f.write(f"Output Size: {input_size} (2 * {n_svd_components})\n")
        f.write(f"Final Training Loss: {train_losses[-1]:.6f}\n")
        f.write(f"Final Testing Loss: {test_losses[-1]:.6f}\n")
        f.write(f"Number of Parameters: {sum(p.numel() for p in model.parameters())}\n")
        f.write(f"Dataset U Explained Variance: {u_svd.explained_variance_ratio_.sum():.4f}\n")
        f.write(f"Dataset V Explained Variance: {v_svd.explained_variance_ratio_.sum():.4f}\n")
        f.write("\nDataset 0 Error Metrics:\n")
        for metric, value in error_metrics0.items():
            f.write(f"{metric}: {value:.6f}\n")

        f.write("\nDataset 1 Error Metrics:\n")
        for metric, value in error_metrics1.items():
            f.write(f"{metric}: {value:.6f}\n")

    print(f"All files saved successfully to the '{save_dir}' directory!")
    print(f"Model saved as: {model_path}")
    print(f"Loss curves saved as: {os.path.join(save_dir, 'loss_curves.png')}")
    print(f"Prediction visualizations saved as:")
    print(f"  - {os.path.join(save_dir, 'prediction_visualization_dataset0.png')}")
    print(f"  - {os.path.join(save_dir, 'prediction_visualization_dataset1.png')}")
    print(f"Loss data saved as: {os.path.join(save_dir, 'loss_data.csv')}")
    print(f"Prediction data saved as:")
    print(f"  - {os.path.join(save_dir, 'u_prediction_data_dataset0.csv')}")
    print(f"  - {os.path.join(save_dir, 'v_prediction_data_dataset0.csv')}")
    print(f"  - {os.path.join(save_dir, 'u_prediction_data_dataset1.csv')}")
    print(f"  - {os.path.join(save_dir, 'v_prediction_data_dataset1.csv')}")
    print(f"Error metrics saved as:")
    print(f"  - {os.path.join(save_dir, 'error_metrics_dataset0.txt')}")
    print(f"  - {os.path.join(save_dir, 'error_metrics_dataset1.txt')}")
    print(f"Model information saved as: {os.path.join(save_dir, 'model_info.txt')}")

if __name__ == "__main__":
    main()
